FROM node:14.16.0-slim

# Create app directory and cd inside
WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

# install all the dependencies
RUN yarn install

# copy all folder contents
COPY . .

# build the application
RUN yarn build

CMD ["yarn", "start"]
