FROM node:14.16.0-slim

# Create app directory and cd inside
WORKDIR /usr/src/app

# copy all folder contents
COPY . .

# install all the dependencies and build the application
RUN yarn install
RUN yarn build

CMD ["yarn", "start"]
